---
include:
  - board: levels54_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SETTINGS_RESET_ON_START=y
  - board: levels54_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SETTINGS_RESET_ON_START=y