---
include:
  - board: levels54_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: levels54_right
  - board: levels54_left
    shield: settings_reset
  - board: levels54_right
    shield: settings_reset
