---
include:
  - board: levels54_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: levels54_right
  - board: levels54_left
    name: levels54_left_settings_reset
    cmake-args: -DCONFIG_ZMK_SETTINGS_RESET_ON_START=y
  - board: levels54_right
    name: levels54_right_settings_reset
    cmake-args: -DCONFIG_ZMK_SETTINGS_RESET_ON_START=y
